### ISSUE TITLE
Implement Send for ExpandAddressOptions

### ISSUE THREAD

**Issue by alucryd** [pnordahl/rust-postal#7]
Hi, I'm trying to use this in a async_graphql context, however I can't use expand_address at all because it expects all structs to implement Send:

```
future cannot be sent between threads safely
within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `*mut *mut i8`
```

I was able to share the postal context using an Arc<Mutex<>>, but it's not possibleto do the same for the options. Could you have a look at it?

**Comment by pnordahl** [comment]
Hey @alucryd, thanks for the issue submission. Unfortunately, the raw pointers within `ExpandAddressOptions` will never be `Send` due to Rust safety rules. One workaround would be to create a new instance of the options in each thread. These are pretty cheap structs, FWIW.

You say that it's not possible to wrap the options in Arc<Mutex<>>; can you show the error you're getting when doing so?
